import type { Product } from "../../types/product";
import men_bracelet_black_silver from "../../assets/images/products/bracelets/men_bracelet_black_silver.jpg"
import men_bracelet_silver_cross from "../../assets/images/products/bracelets/men_bracelet_silver_cross.jpg"
import men_cufflinks_yerevan from "../../assets/images/products/cufflinks/men_cufflinks_yerevan.jpg"
import cross_gold from "../../assets/images/products/pendants/cross_gold.jpg"
export const PRODUCT_LIST: Product[] = [
  {
    id: Date.now(),
    name: "Black Silver Bracelet",
    images: [
      men_bracelet_black_silver, men_bracelet_silver_cross, men_cufflinks_yerevan,men_cufflinks_yerevan, men_cufflinks_yerevan
    ],
    price: 1290,
    availability: "in_stock",
    attributes: {
      metal: "White Gold",
      stone: "Diamond",
      weight: "3.1 g",
      size: "16",
      purity: "14K",
    },
    description: "Classic diamond solitaire ring crafted in 14K white gold.",
    category: "Rings",
    collection: "Elegance",
    sku: "RG-DM-001",
    similarProducts: ["2", "3"],
  },
  {
    id: 2,
    name: "Emerald Cut Engagement Ring",
    images: [cross_gold],
    price: 1890,
    availability: "in_stock",
    attributes: {
      metal: "Yellow Gold",
      stone: "Diamond",
      weight: "3.6 g",
      size: "17",
      purity: "18K",
    },
    description: "Elegant emerald-cut diamond engagement ring.",
    category: "Rings",
    collection: "Bridal",
    sku: "RG-DM-002",
    similarProducts: ["1", "4"],
  },
  {
    id: 3,
    name: "Ruby Halo Ring",
    images: [men_cufflinks_yerevan],
    price: 950,
    availability: "in_stock",
    attributes: {
      metal: "Rose Gold",
      stone: "Ruby",
      weight: "2.8 g",
      size: "16.5",
      purity: "14K",
      color: "Red",
    },
    description: "Ruby centerpiece with a sparkling diamond halo.",
    category: "Rings",
    collection: "Royal",
    sku: "RG-RB-003",
    similarProducts: ["1"],
  },
  {
    id: 4,
    name: "Diamond Tennis Bracelet",
    images: [
      men_bracelet_silver_cross,
    ],
    price: 2800,
    availability: "out_of_stock",
    attributes: {
      metal: "White Gold",
      stone: "Diamond",
      weight: "9.2 g",
      purity: "18K",
      dimensions: "18 cm",
    },
    description: "18K white gold tennis bracelet with brilliant diamonds.",
    category: "Bracelets",
    collection: "Luxury",
    sku: "BR-DM-004",
    similarProducts: ["5"],
  },
  {
    id: 5,
    name: "Gold Bangle",
    images: [men_bracelet_silver_cross],
    price: 720,
    availability: "in_stock",
    attributes: {
      metal: "Yellow Gold",
      weight: "7.1 g",
      purity: "14K",
      size: "18",
    },
    description: "Simple and elegant solid gold bangle.",
    category: "Bracelets",
    sku: "BR-GL-005",
    similarProducts: ["4"],
  },
  {
    id: 6,
    name: "Pearl Drop Earrings",
    images: [cross_gold],
    price: 410,
    availability: "in_stock",
    attributes: {
      metal: "Silver",
      stone: "Pearl",
      weight: "2.4 g",
      color: "White",
    },
    description: "Elegant pearl drop earrings for timeless beauty.",
    category: "Earrings",
    sku: "ER-PL-006",
    similarProducts: ["7", "8"],
  },
  {
    id: 7,
    name: "Diamond Stud Earrings",
    images: [men_cufflinks_yerevan],
    price: 780,
    availability: "in_stock",
    attributes: {
      metal: "White Gold",
      stone: "Diamond",
      purity: "14K",
      weight: "1.2 g",
    },
    description: "Timeless diamond studs set in white gold.",
    category: "Earrings",
    sku: "ER-DM-007",
    similarProducts: ["6"],
  },
  {
    id: 8,
    name: "Sapphire Hoop Earrings",
    images: [men_bracelet_silver_cross],
    price: 920,
    availability: "in_stock",
    attributes: {
      metal: "Yellow Gold",
      stone: "Sapphire",
      weight: "3.0 g",
      purity: "18K",
      color: "Blue",
    },
    description: "Hoop earrings with deep blue sapphires.",
    category: "Earrings",
    sku: "ER-SP-008",
    similarProducts: ["6"],
  },
  {
    id: 9,
    name: "Heart Pendant Necklace",
    images: [men_bracelet_black_silver ],
    price: 260,
    availability: "in_stock",
    attributes: {
      metal: "Silver",
      weight: "2.1 g",
      dimensions: "45 cm",
    },
    description: "Delicate silver heart pendant necklace.",
    category: "Necklaces",
    sku: "NL-SL-009",
    similarProducts: ["10", "11"],
  },
  {
    id: 10,
    name: "Infinity Gold Necklace",
    images: [men_cufflinks_yerevan],
    price: 540,
    availability: "in_stock",
    attributes: {
      metal: "Yellow Gold",
      purity: "14K",
      weight: "2.9 g",
      dimensions: "45 cm",
    },
    description: "Minimalist gold infinity symbol necklace.",
    category: "Necklaces",
    sku: "NL-GL-010",
    similarProducts: ["9"],
  },
  {
    id: 11,
    name: "Emerald Pendant Necklace",
    images: [men_bracelet_silver_cross],
    price: 840,
    availability:"in_stock",
    attributes: {
      metal: "White Gold",
      stone: "Emerald",
      purity: "18K",
      weight: "3.0 g",
    },
    description: "Emerald pendant with diamond accents.",
    category: "Necklaces",
    sku: "NL-EM-011",
    similarProducts: ["9"],
  },
  {
    id: 12,
    name: "Men's Signet Ring",
    images: [men_bracelet_black_silver ],
    price: 620,
    availability: "in_stock",
    attributes: {
      metal: "Silver",
      weight: "6.5 g",
      size: "20",
      color: "Silver",
    },
    description: "Bold silver signet ring with classic design.",
    category: "Rings",
    sku: "RG-MN-012",
    similarProducts: ["13"],
  },
  // {
  //   id: 13,
  //   name: "Black Onyx Men's Ring",
  //   images: ["../../assets/images/products/pendants/cross_gold.jpg"],
  //   price: 690,
  //   availability: true,
  //   attributes: {
  //     metal: "Silver",
  //     stone: "Onyx",
  //     weight: "7.0 g",
  //     size: "21",
  //   },
  //   description: "Men's ring featuring a polished black onyx stone.",
  //   category: "Rings",
  //   sku: "RG-ON-013",
  //   similarProducts: ["12"],
  // },
  // {
  //   id: 14,
  //   name: "Gold Chain Necklace",
  //   images: ["../../assets/images/products/pendants/cross_gold.jpg"],
  //   price: 980,
  //   availability: true,
  //   attributes: {
  //     metal: "Yellow Gold",
  //     purity: "18K",
  //     weight: "8.5 g",
  //     dimensions: "50 cm",
  //   },
  //   description: "18K yellow gold chain with bold links.",
  //   category: "Necklaces",
  //   sku: "NL-GL-014",
  //   similarProducts: ["10"],
  // },
  // {
  //   id: 15,
  //   name: "Sapphire Engagement Ring",
  //   images: ["../../assets/images/products/pendants/cross_gold.jpg"],
  //   price: 1550,
  //   availability: true,
  //   attributes: {
  //     metal: "White Gold",
  //     stone: "Sapphire",
  //     purity: "18K",
  //     weight: "3.3 g",
  //   },
  //   description: "Romantic sapphire ring with diamond halo.",
  //   category: "Rings",
  //   sku: "RG-SP-015",
  //   similarProducts: ["2"],
  // },
  // {
  //   id: 16,
  //   name: "Opal Pendant",
  //   images: ["../../assets/images/products/pendants/cross_gold.jpg"],
  //   price: 420,
  //   availability: true,
  //   attributes: {
  //     metal: "Silver",
  //     stone: "Opal",
  //     weight: "2.0 g",
  //   },
  //   description: "Fire opal pendant with mystical color play.",
  //   category: "Necklaces",
  //   sku: "NL-OP-016",
  //   similarProducts: ["11"],
  // },
  // {
  //   id: 17,
  //   name: "Diamond Eternity Ring",
  //   images: ["../../assets/images/products/pendants/cross_gold.jpg"],
  //   price: 2000,
  //   availability: false,
  //   attributes: {
  //     metal: "White Gold",
  //     stone: "Diamond",
  //     purity: "18K",
  //     weight: "2.9 g",
  //   },
  //   description: "Full eternity diamond ring symbolizing forever.",
  //   category: "Rings",
  //   sku: "RG-DM-017",
  //   similarProducts: ["1"],
  // },
  // {
  //   id: 18,
  //   name: "Emerald Stud Earrings",
  //   images: [men_cufflinks_yerevan],
  //   price: 720,
  //   availability: true,
  //   attributes: {
  //     metal: "Yellow Gold",
  //     stone: "Emerald",
  //     purity: "18K",
  //   },
  //   description: "Vibrant emerald stud earrings in gold settings.",
  //   category: "Earrings",
  //   sku: "ER-EM-018",
  //   similarProducts: ["7"],
  // },
  // {
  //   id: 19,
  //   name: "Pearl Choker Necklace",
  //   images: ["../../assets/images/products/pendants/cross_gold.jpg"],
  //   price: 670,
  //   availability: true,
  //   attributes: {
  //     metal: "Silver",
  //     stone: "Pearl",
  //     weight: "4.1 g",
  //   },
  //   description: "Classic pearl choker for formal occasions.",
  //   category: "Necklaces",
  //   sku: "NL-PR-019",
  //   similarProducts: ["6"],
  // },
  // {
  //   id: 20,
  //   name: "Rose Gold Bracelet",
  //   images: ["../../assets/images/products/bracelets/men_bracelet_gold.jpg"],
  //   price: 530,
  //   availability: true,
  //   attributes: {
  //     metal: "Rose Gold",
  //     purity: "14K",
  //     weight: "5.4 g",
  //     dimensions: "17 cm",
  //   },
  //   description: "Modern rose gold bracelet with smooth finish.",
  //   category: "Bracelets",
  //   sku: "BR-RG-020",
  //   similarProducts: ["5"],
  // },
  // {
  //   id: 21,
  //   name: "Amethyst Ring",
  //   images: ["../../assets/images/products/pendants/cross_gold.jpg"],
  //   price: 450,
  //   availability: true,
  //   attributes: {
  //     metal: "Silver",
  //     stone: "Amethyst",
  //     weight: "2.8 g",
  //     size: "17",
  //   },
  //   description: "Purple amethyst ring with vintage details.",
  //   category: "Rings",
  //   sku: "RG-AM-021",
  //   similarProducts: ["3"],
  // },
  // {
  //   id: 22,
  //   name: "Topaz Pendant Necklace",
  //   images: ["../../assets/images/products/pendants/cross_gold.jpg"],
  //   price: 390,
  //   availability: true,
  //   attributes: {
  //     metal: "Silver",
  //     stone: "Topaz",
  //     weight: "2.5 g",
  //   },
  //   description: "Sky-blue topaz set in polished silver.",
  //   category: "Necklaces",
  //   sku: "NL-TP-022",
  //   similarProducts: ["16"],
  // },
  // {
  //   id: 23,
  //   name: "Diamond Wedding Band",
  //   images: ["../../assets/images/products/pendants/cross_gold.jpg"],
  //   price: 1150,
  //   availability: true,
  //   attributes: {
  //     metal: "White Gold",
  //     stone: "Diamond",
  //     purity: "14K",
  //     weight: "2.2 g",
  //   },
  //   description: "Simple yet elegant diamond wedding band.",
  //   category: "Rings",
  //   sku: "RG-DM-023",
  //   similarProducts: ["17"],
  // },
  // {
  //   id: 24,
  //   name: "Gold Pendant Cross",
  //   images: ["../../assets/images/products/pendants/cross_gold.jpg"],
  //   price: 780,
  //   availability: true,
  //   attributes: {
  //     metal: "Yellow Gold",
  //     purity: "18K",
  //     weight: "3.9 g",
  //     dimensions: "48 cm",
  //   },
  //   description: "Classic Christian cross pendant in 18K gold.",
  //   category: "Necklaces",
  //   sku: "NL-CR-024",
  //   similarProducts: ["14"],
  // },
];

export const COVER_TEXT : string = "Men’s Innovative Materials This curated edit reflects a bold artistic vision, merging meteorite, forged carbon, and more into unmistakably modern designs."
